---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: deploy and configure rvm
  hosts: web_servers
  remote_user: root
  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, become: yes }
    - abtris.nginx-passenger

- name: install the db
  hosts: web_servers
  remote_user: root
  roles:
    - db_setup

- name: install and run the rails app
  hosts: web_servers
  remote_user: root
  roles:
    - app_setup
    - app_web_server
